Repository hacspec/hacspec, pull requests merged in 2022-11, with the labels that each got.

#317 Ssprove typechecker
  language/src/ast_to_rustspec.rs
  language/src/elab_monadic_lets.rs
  language/src/main.rs
  language/src/name_resolution.rs
  language/src/rustspec.rs
  language/src/rustspec_to_coq.rs
  language/src/rustspec_to_easycrypt.rs
  language/src/rustspec_to_fstar.rs
  language/src/typechecker.rs
Labels: typechecker :necktie:, waiting-on-review

#318 Ssprove coq refactor
  language/src/main.rs
  language/src/rustspec_to_coq.rs
  language/src/rustspec_to_coq_base.rs
Labels: waiting-on-review

#295 Merlin 1/2 - Transcript creation and appending
  examples/Cargo.toml
  examples/merlin/Cargo.toml
  examples/merlin/src/merlin.rs
  examples/merlin/src/strobe.rs
  examples/typecheck_examples.sh
Labels: waiting-on-author

#296 Merlin 2/2 - Get data from Transcript and added test
  examples/merlin/src/merlin.rs
  examples/merlin/src/strobe.rs
  examples/merlin/tests/test_prop_merlin.rs
Labels: waiting-on-author

#313 Ssprove ci ssprove
  .github/workflows/generate_examples_ssprove.yml
  coq_ssprove/docker_build/Dockerfile
Labels: ci ⚙️, blocked
